apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: notifyflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: dockerhuburl/notifyflow-api-gateway:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifyflow-config
            - secretRef:
                name: notifyflow-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: notifyflow
spec:
  selector:
    app: api-gateway
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
