apiVersion: v1
kind: Secret
metadata:
  name: notifyflow-secrets
  namespace: notifyflow
type: Opaque
stringData:
  JWT_SECRET: "secret"
  DB_USER: "root"
  DB_PASS: "root"
  ACTIVEMQ_USER: "user"
  ACTIVEMQ_PASS: "password"
